# Generated by Django 5.1.2 on 2024-10-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
